puts "Seeding Challenges from Kitt"
challenges = []
challenges << { module: "Ruby", skill: "Programming Basics", name: "Who's your buddy?", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2F01-Buddy" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Experiment Methods", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2F02-Experiment-methods" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Age in Days", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2F03-Age-in-days" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "What is your Name", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2F04-What-your-name" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Stupid Coaching", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2F05-Stupid-coaching" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Colourful Algorithm", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2FOptional-01-Colorful-Algorithm" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "IP Address Converter", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2FOptional-02-Ip-Address-Converter" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Morse Code", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2FOptional-04-Morse-Code" }
challenges << { module: "Ruby", skill: "Programming Basics", name: "Valid Brackets", url_fragment: "/challenges?path=01-Ruby%2F01-Programming-basics%2FOptional-05-Valid-Brackets" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Can you vote?", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F01-Can-you-vote" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Simple Looping", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F02-Simple-looping" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Sorting the Wagon", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F03-Sorting-the-wagon" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Black Jack", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F04-Black-Jack" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Debug Gym", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F05-Debug-Gym" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Destructive Methods", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2F06-Destructive-Methods" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Roman Numerals", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2FOptional-01-Roman-numerals" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Shuffle", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2FOptional-02-Shuffle" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Beer Song", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2FOptional-03-Beer-song" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Fizz Buzz", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2FOptional-04-Fizz-Buzz" }
challenges << { module: "Ruby", skill: "Flow, Conditionals & Arrays", name: "Recursion", url_fragment: "/challenges?path=01-Ruby%2F02-Flow-Array%2FOptional-05-Simple-Looping-With-Recursion" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Team Members", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F01-How-many-team-members" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Enumerable Methods", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F02-Enumerable" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Burger Restaurant", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F03-Burger-restaurant" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "HTML Generator", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F04-HTML-generator" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Splitter", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F05-Splitter" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Playing with Strings", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2FOptional-01-Playing-with-strings" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Louchebem", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2F06-Louchebem" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "Storing Blocks in Procs", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2FOptional-02-Storing-blocks-in-Proc" }
challenges << { module: "Ruby", skill: "Iterators & Blocks", name: "A Custom Map", url_fragment: "/challenges?path=01-Ruby%2F03-Iterators-Blocks%2FOptional-03-A-custom-map" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Burger Hash", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2F01-Modeling-with-Hash" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Burger Hash (Part II)", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2F02-Modeling-with-Hash-part-II" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Quiz on Symbols", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2F03-On-symbols" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Argument Order Dependency", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2F04-Argument-order-dependency" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Array to Hash", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2F05-Array-to-hash" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Roman to Integer", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2FOptional-01-Roman-to-integer" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Combine Anagrams", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2FOptional-02-Combine-anagrams" }
challenges << { module: "Ruby", skill: "Hash & Symbols", name: "Shopping Cart", url_fragment: "/challenges?path=01-Ruby%2F04-Hash-Symbols%2FOptional-03-Shopping-Cart" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Phone Regexp", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2F01-Phone-regexp" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Marketing Campaign", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2F02-Marketing-campaign" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Double Rainbow", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2F04-Double-Rainbow" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Word Frequency", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2F03-Word-frequency" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Regex Games", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2FOptional-01-Regex-Games" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Calculator", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2FReboot-01-Calculator" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Horse Race", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2FReboot-02-Horse-race" }
challenges << { module: "Ruby", skill: "Regular Expressions", name: "Instacart", url_fragment: "/challenges?path=01-Ruby%2F05-Regular-Expressions%2FReboot-03-Instacart" }
challenges << { module: "Ruby", skill: "Parsing", name: "CSV Parsing", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2F01-CSV-Parsing" }
challenges << { module: "Ruby", skill: "Parsing", name: "Numbers and Letters", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2F02-Numbers-and-Letters" }
challenges << { module: "Ruby", skill: "Parsing", name: "Text Analyser", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2FOptional-01-Text-Analyzer" }
challenges << { module: "Ruby", skill: "Parsing", name: "Your First Scraper", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2FOptional-02-Your-First-Scraper" }
challenges << { module: "Ruby", skill: "Parsing", name: "Time Complexity", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2FOptional-03-Time-complexity" }
challenges << { module: "Ruby", skill: "Parsing", name: "Christmas List", url_fragment: "/challenges?path=01-Ruby%2F06-Parsing%2FReboot-01-Christmas-list" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Define your own Class", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2F01-Define-your-own-class" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Getters and Setters", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2F02-Getters-and-Setters" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Basic OOP", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2F03-Basic-OOP" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Public Interface", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2F04-Public-Interface" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Richest Student", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2FOptional-01-Richest-Student" }
challenges << { module: "OOP", skill: "Classes & Instances", name: "Method Missing", url_fragment: "/challenges?path=02-OOP%2F01-OO-Basics%2FOptional-02-Method-Missing" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Dog Inheritance", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2F01-Dog-inheritance" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Farming Diary Crops", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2F02-Farming-Diary-Crops" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Instance vs Class", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2F04-Instance-vs-Class" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Farming Diary Animals", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2F03-Farming-Diary-Animals" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "About self", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2F05-About-self" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Farming Diary Game", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2FOptional-03-Farming-Diary-Game" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Tracking Subclasses", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2FOptional-04-Tracking-Subclasses" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Web Browser", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2FOptional-01-Web-Browser" }
challenges << { module: "OOP", skill: "Inheritance & Self", name: "Gosu Game", url_fragment: "/challenges?path=02-OOP%2F02-OO-Advanced%2FOptional-02-Gosu-Game" }
challenges << { module: "OOP", skill: "Cookbook (Day 1)", name: "Start with the Model", url_fragment: "/challenges?path=02-OOP%2F03-Cookbook-Day-One%2F01-Recipe" }
challenges << { module: "OOP", skill: "Cookbook (Day 1)", name: "Cookbook Day 1", url_fragment: "/challenges?path=02-OOP%2F03-Cookbook-Day-One%2F02-Cookbook" }
challenges << { module: "OOP", skill: "Cookbook (Day 1)", name: "Pocket Reader", url_fragment: "/challenges?path=02-OOP%2F03-Cookbook-Day-One%2FOptional-01-Medium-pocket" }
challenges << { module: "OOP", skill: "Cookbook (Day 2)", name: "Cookbook Day 2", url_fragment: "/challenges?path=02-OOP%2F04-Cookbook-Day-Two%2F01-Cookbook-Advanced" }
challenges << { module: "OOP", skill: "Cookbook (Day 2)", name: "Cookbook Web App", url_fragment: "/challenges?path=02-OOP%2F04-Cookbook-Day-Two%2FOptional-01-Sinatra" }
challenges << { module: "OOP", skill: "Food Delivery (Day 1)", name: "Food Delivery Day 1", url_fragment: "/challenges?path=02-OOP%2F05-Food-Delivery-Day-One%2F01-Food-Delivery" }
challenges << { module: "OOP", skill: "Food Delivery (Day 1)", name: "Pocket Reader (extended)", url_fragment: "/challenges?path=02-OOP%2F05-Food-Delivery-Day-One%2FOptional-01-Medium-pocket-part-two" }
challenges << { module: "OOP", skill: "Food Delivery (Day 2)", name: "Food Delivery Day 2", url_fragment: "/challenges?path=02-OOP%2F06-Food-Delivery-Day-Two%2F01-Food-Delivery" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "Table Design", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2F01-Your-first-table" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "DB Design", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2F02-SQL-design" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "Interacting with DB", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2F03-Interacting-with-db" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "Interacting with Code", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2F04-Interacting-with-code" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "SQL Queries", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2F05-SQL-queries" }
challenges << { module: "DB", skill: "Schema Design & SQL", name: "Jukebox Sinatra", url_fragment: "/challenges?path=03-AR-Database%2F01-DB-Design-and-SQL%2FOptional-01-Jukebox-Sinatra" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "Query the DB", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2F01-Query-the-DB" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "Read", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2F02-Read" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "Delete", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2F03-Delete" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "Create Update", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2F04-Create-Update" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "MVC HackerNews", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2F05-MVC-HackerNews" }
challenges << { module: "DB", skill: "CRUD with SQL", name: "My First ORM", url_fragment: "/challenges?path=03-AR-Database%2F02-SQL-CRUD%2FOptional-01-My-First-ORM" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Generate DB", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2F01-Create-a-DB" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Migrations", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2F02-Migrations" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Models", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2F03-Models" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Seed Faker", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2F04-Seed-Faker" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Seed API", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2F05-Seed-API" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Mapping Existing DataBase", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2FOptional-01-Mapping-Existing-Database" }
challenges << { module: "DB", skill: "Active Record Basics", name: "Mapping Dirty DataBase", url_fragment: "/challenges?path=03-AR-Database%2F03-ActiveRecord-Basics%2FOptional-02-Mapping-Dirty-Database" }
challenges << { module: "DB", skill: "Associations & Validations", name: "Associations", url_fragment: "/challenges?path=03-AR-Database%2F04-ActiveRecord-Advanced%2F01-Associations" }
challenges << { module: "DB", skill: "Associations & Validations", name: "Validations", url_fragment: "/challenges?path=03-AR-Database%2F04-ActiveRecord-Advanced%2F02-Validations" }
challenges << { module: "DB", skill: "Associations & Validations", name: "Sinatra", url_fragment: "/challenges?path=03-AR-Database%2F04-ActiveRecord-Advanced%2F03-Sinatra" }
challenges << { module: "DB", skill: "Associations & Validations", name: "Reading Material", url_fragment: "/challenges?path=03-AR-Database%2F04-ActiveRecord-Advanced%2FOptional-01-Reading-Material" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Profile Content", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F01-Profile-content" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Fonts and Colours", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F02-Fonts-and-colors" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Finishing Profile Design", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F03-Finishing-profile-design" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Responsive Profile", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F04-Responsive-profile" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Push to GitHub Pages", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F05-Push-on-Github-Pages" }
challenges << { module: "Front", skill: "HTML & CSS", name: "Medium Copycat", url_fragment: "/challenges?path=04-Front-End%2F01-HTML-and-CSS%2F06-Medium-copycat" }
challenges << { module: "Front", skill: "CSS Components", name: "Button Sprint", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F01-Button-sprint" }
challenges << { module: "Front", skill: "CSS Components", name: "Card Sprint", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F02-Card-sprint" }
challenges << { module: "Front", skill: "CSS Components", name: "Landing Page Design", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F03-Landing-page" }
challenges << { module: "Front", skill: "CSS Components", name: "Dribbble Activity Feed", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F04-Activity-feed" }
challenges << { module: "Front", skill: "CSS Components", name: "Copycat Challenge", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F05-Open-component-challenge" }
challenges << { module: "Front", skill: "CSS Components", name: "Take Away", url_fragment: "/challenges?path=04-Front-End%2F02-CSS-components%2F06-Take-away" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Smiley Grids", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2F01-Smiley-grids" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Bootstrap Prototyping", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2F02-Bootstrap-prototyping" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Bootstrap Forms", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2F03-Bootstrap-forms" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Map Layout", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2F04-Map-layout" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Slack", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2FOptional-01-Slack-copycat" }
challenges << { module: "Front", skill: "Bootstrap & Layouts", name: "Accessibility", url_fragment: "/challenges?path=04-Front-End%2F03-Bootstrap%2FOptional-02-Accessibility" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Even or odd?", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F01-Even-or-odd" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Looping", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F02-Sum-of-negative" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Valid Email", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F03-Valid-email" }
challenges << { module: "Front", skill: "JavaScript basics", name: "List generator", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F04-Unordered-list" }
challenges << { module: "Front", skill: "JavaScript basics", name: "The Lord of the Rings", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F05-Lord-of-the-rings" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Data extractor", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2F06-Dataset" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Age in days 2", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2FOptional-01-Age-In-Days" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Split the bill", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2FOptional-02-Split-The-Bill" }
challenges << { module: "Front", skill: "JavaScript basics", name: "Bowling calculator", url_fragment: "/challenges?path=04-Front-End%2F04-JavaScript-basics%2FOptional-03-Bowling-Calculator" }
challenges << { module: "Front", skill: "DOM & Events", name: "Select an element!", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2F01-Select-element" }
challenges << { module: "Front", skill: "DOM & Events", name: "DOM Manipulation", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2F02-DOM-Manipulation" }
challenges << { module: "Front", skill: "DOM & Events", name: "My first event listener", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2F03-My-First-Event-Listener" }
challenges << { module: "Front", skill: "DOM & Events", name: "Wagon race", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2F04-Wagon-Race" }
challenges << { module: "Front", skill: "DOM & Events", name: "Fake Inbox", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2F05-Fake-Inbox" }
challenges << { module: "Front", skill: "DOM & Events", name: "Form validation", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2FOptional-01-Form-Validation" }
challenges << { module: "Front", skill: "DOM & Events", name: "Minesweeper", url_fragment: "/challenges?path=04-Front-End%2F05-DOM-and-Events%2FOptional-02-Minesweeper" }
challenges << { module: "Front", skill: "HTTP & AJAX", name: "Click me!", url_fragment: "/challenges?path=04-Front-End%2F06-HTTP-and-AJAX%2F01-Click-me" }
challenges << { module: "Front", skill: "HTTP & AJAX", name: "My Favourite Sports", url_fragment: "/challenges?path=04-Front-End%2F06-HTTP-and-AJAX%2F02-My-Favourite-Sports" }
challenges << { module: "Front", skill: "HTTP & AJAX", name: "AJAX Autocomplete", url_fragment: "/challenges?path=04-Front-End%2F06-HTTP-and-AJAX%2F03-AJAX-Autocomplete" }
challenges << { module: "Front", skill: "HTTP & AJAX", name: "Anonymous Chat", url_fragment: "/challenges?path=04-Front-End%2F06-HTTP-and-AJAX%2F04-Promo-Chat" }
challenges << { module: "Front", skill: "HTTP & AJAX", name: "Booking Form", url_fragment: "/challenges?path=04-Front-End%2F06-HTTP-and-AJAX%2FOptional-01-Booking-form" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "Bugfix", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2F01-Bugfix" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "ES6 Classes", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2F03-Classes" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "StimulusJS", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2F04-Stimulus" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "Geocoder", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2F02-Geocoder" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "Weather Forecast", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2F05-Weather" }
challenges << { module: "Front", skill: "JavaScript Packages", name: "AJAX Wagon race", url_fragment: "/challenges?path=04-Front-End%2F07-JavaScript-Plugins%2FOptional-01-AJAX-wagon-race" }
challenges << { module: "Rails", skill: "Routing, Controllers & Views", name: "HTTP and MVC quiz", url_fragment: "/challenges?path=05-Rails%2F01-Rails-intro%2F01-HTTP-and-MVC-quiz" }
challenges << { module: "Rails", skill: "Routing, Controllers & Views", name: "Stupid Coaching", url_fragment: "/challenges?path=05-Rails%2F01-Rails-intro%2F02-Stupid-coaching" }
challenges << { module: "Rails", skill: "Routing, Controllers & Views", name: "Longest Word Game", url_fragment: "/challenges?path=05-Rails%2F01-Rails-intro%2F03-Longest-word-game" }
challenges << { module: "Rails", skill: "Models & CRUD", name: "Routing Quiz", url_fragment: "/challenges?path=05-Rails%2F02-Rails-CRUD%2F01-Routing-quiz" }
challenges << { module: "Rails", skill: "Models & CRUD", name: "Rails Task Manager", url_fragment: "/challenges?path=05-Rails%2F02-Rails-CRUD%2F02-Rails-Task-Manager" }
challenges << { module: "Rails", skill: "Models & CRUD", name: "Rails Wikinimous", url_fragment: "/challenges?path=05-Rails%2F02-Rails-CRUD%2F03-Rails-Wikinimous" }
challenges << { module: "Rails", skill: "Advanced Routing", name: "CRUD Quiz", url_fragment: "/challenges?path=05-Rails%2F03-Rails-restaurant-reviews%2F01-CRUD-quiz" }
challenges << { module: "Rails", skill: "Advanced Routing", name: "Yelp MVP", url_fragment: "/challenges?path=05-Rails%2F03-Rails-restaurant-reviews%2F02-Yelp-MVP" }
challenges << { module: "Rails", skill: "Advanced Routing", name: "Rails Simple Airbnb", url_fragment: "/challenges?path=05-Rails%2F03-Rails-restaurant-reviews%2F03-Simple-Airbnb" }
challenges << { module: "Rails", skill: "Front-End", name: "Advanced Routing Quiz", url_fragment: "/challenges?path=05-Rails%2F04-Rails-mister-cocktail%2F01-Advanced-routing-quiz" }
challenges << { module: "Rails", skill: "Front-End", name: "Watch List", url_fragment: "/challenges?path=05-Rails%2F04-Rails-mister-cocktail%2F02-Watch-List" }
challenges << { module: "Rails", skill: "Hosting & Image Upload", name: "Rails Frontend Quiz", url_fragment: "/challenges?path=05-Rails%2F05-Rails-MC-with-images%2F01-Rails-frontend-quiz" }
challenges << { module: "Rails", skill: "Hosting & Image Upload", name: "Watch List w/ Images", url_fragment: "/challenges?path=05-Rails%2F05-Rails-MC-with-images%2F02-Watch-List-Images" }
Challenge.upsert_all challenges
puts "#{Challenge.all.count} Challenges added to database."
